### PR TITLE
Ability to filter Activity Log by "id"

### PR DESCRIPTION
**Pull request by dcodeaaron**
Provides ability to filter Activity Logs by "id".

Because of this the `modelId` query is now only `required` when `filter[id]` query is not supplied.

Example GET request.

`/api/generic/activity-logs?modelClass=App\Models\Enquiry\Enquiry&filter[id]=1009`

Relates to: https://github.com/DCODE-GROUP/precision-scaffolding/pull/267

### CODE REVIEW

**Comment by lionslair** [comment]
Why would you not be getting results for a given model? Where would you want to show all models of a type?

**Comment by dcodeaaron** [comment]
> Why would you not be getting results for a given model? Where would you want to show all models of a type?

The goal here is to determine if an activity log exists that's associated with the given model (e.g Enquiry) and with the given `id`.

Should that model exist then in the Precision app we're displaying the Enquiry associated with that individual activity log.

Because of the above it's the `modelId` that's the unknown and what we're looking for in the Precision app.

**Comment by lionslair** [comment]
> > Why would you not be getting results for a given model? Where would you want to show all models of a type?
> 
> The goal here is to determine if an activity log exists that's associated with the given model (e.g Enquiry) and with the given `id`.
> 
> Should that model exist then in the Precision app we're displaying the Enquiry associated with that individual activity log.
> 
> Because of the above it's the `modelId` that's the unknown and what we're looking for in the Precision app.

Think you are maybe using it wrong

**Comment by dcodeaaron** [comment]
> > > Why would you not be getting results for a given model? Where would you want to show all models of a type?
> > 
> > 
> > The goal here is to determine if an activity log exists that's associated with the given model (e.g Enquiry) and with the given `id`.
> > Should that model exist then in the Precision app we're displaying the Enquiry associated with that individual activity log.
> > Because of the above it's the `modelId` that's the unknown and what we're looking for in the Precision app.
> 
> Think you are maybe using it wrong

Have talked this through with Nathan and we're on the same page now.

**Review by andrewsirianni — APPROVED** [review]

**Pull request merged**
